spring.application.name=rent-city
# Ket noi Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/rent_city
spring.datasource.username=postgres
spring.datasource.password=
# Tu dong tao/cap nhat bang dua tren Code Java
spring.jpa.hibernate.ddl-auto=update
# Hien cau lenh SQL duoi Console
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
